name: mynotas_app
description: App de notas con CRUD y sqflite
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path_provider: ^2.0.15
  path: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
